# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go generate ./...
build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - >-
      -w -s
      -X github.com/duckpuppy/{{.ProjectName}}/cmd.Version={{.Version}}
      -X github.com/duckpuppy/{{.ProjectName}}/cmd.Build={{.Date}}
      -X github.com/duckpuppy/{{.ProjectName}}/cmd.Commit={{printf "%.7s" .Commit}}
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
